# Generated by Django 2.1 on 2019-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BattlleField', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbattlefield',
            name='about_room',
            field=models.TextField(max_length=56),
        ),
    ]
