# Generated by Django 2.2 on 2019-05-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDungeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=20)),
                ('about_room', models.TextField(max_length=65)),
                ('image_room', models.ImageField(upload_to='dungeon_media')),
            ],
        ),
    ]
